[package]
name = "rust-sumcheck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-bls12-381 = "0.4.0"
ark-ff = "0.4.2"
ark-poly = "0.4.2"
merlin = "3.0.0"
ran = "2.0.1"
rand = "0.8.5"
